### ISSUE TITLE
"promped"

### ISSUE THREAD

**Issue by ludoviclafole** [MichaelBitard/chrootAnsible#2]
I don't know this word. This confused me a lot nearly unable to understand what this repository is about 'cause of this.
(On the end of the readme ;) )

**Comment by ludoviclafole** [comment]
I forgot : "Prerequisites" at start ^^.

**Comment by ludoviclafole** [comment]
and "chose" in usage :p

**Comment by MichaelBitard** [comment]
Where is the pull request? :)

**Comment by ludoviclafole** [comment]
OK OK, you won i'll make one.
Le 13 janv. 2014 23:30, "Michaël Bitard" notifications@github.com a écrit
:

**Comment by ludoviclafole** [comment]
Done ;).
