### ISSUE TITLE
no need for ssh

### ISSUE THREAD

**Issue by jpcaruana** [MichaelBitard/chrootAnsible#4]
with ansible, you can use ansible_connection=chroot

see http://docs.ansible.com/faq.html

**Comment by MichaelBitard** [comment]
That's great, I'll look into it.

Thanks

**Comment by jpcaruana** [comment]
sinon y'a www.docker.io

**Comment by MichaelBitard** [comment]
Oui j'ai vu, j'aime pas trop les dockerfiles, par contre un mix docker + ansible semble pas mal du tout.
J'ai prévu de faire l'équivalent de ce projet avec docker, voir ce que ça donne.

**Comment by jpcaruana** [comment]
yep : pressé de voir ça. Je ne vois pas encore bien comment faire interagir les 2 ensemble.
j'ai la désagréable impression qu'il faut utiliser les dockerfile pour bénéficier du cache de docker

http://devo.ps/blog/2013/09/25/vagrant-docker-and-ansible-wtf.html

**Comment by MichaelBitard** [comment]
Bon, j'aurai mis le temps mais : 

J'ai crée un repo docker + ansible (on commence à l'utiliser chez mon client actuel)
J'ai eu quelques soucis avec les applications graphiques et pour rentrer dans docker sans ssh mais depuis la 1.3.0 et docker exec c'est bon.
Si ça t'intéresse le bootstrap est là : https://github.com/MichaelBitard/docker-ansible

Au final en effet on "perd" le cache docker, mais ce n'est pas quelque chose d'important pour la configuration d'un poste de dev (et tu peux toujours à la fin commiter ton instance pour la "transformer" en image)

Ha oui, un jour peut être que je modifierai cette chroot pour intégrer ton ansible_connection=chroot :)

**Comment by jpcaruana** [comment]
nice ! :+1:
